annotations: {}
labels: {}
meta:
  acl:
  - action: allow
    permissions:
    - read
    - write
    subjects:
    - hmnid
  id: yandexpay-sprint-production-rule-bionic-app
  inherit_acl: true
  stage_id: yandexpay-sprint-production
spec:
  auto_commit_policy: {}
  patches:
    patch-bionic-app-api:
      sandbox:
        sandbox_resource_type: PORTO_LAYER_SEARCH_UBUNTU_BIONIC_APP
        static:
          deploy_unit_id: api
          layer_ref: bionic-app
    patch-bionic-app-workers:
      sandbox:
        sandbox_resource_type: PORTO_LAYER_SEARCH_UBUNTU_BIONIC_APP
        static:
          deploy_unit_id: workers
          layer_ref: bionic-app
  sandbox:
    release_types:
    - stable
    resource_types:
    - PORTO_LAYER_SEARCH_UBUNTU_BIONIC_APP
    task_type: YA_MAKE_TGZ
