meta:
  account_id: abc:service:32444
  id: yandexpay-sprint-production
  inherit_acl: true
  project_id: yandexpay-sprint
spec:
  deploy_units:
    api:
      endpoint_sets:
      - port: 80
      images_for_boxes:
        api:
          digest: 'EMPTY:'
          name: yandex-pay-sprint/yandex-pay-sprint
          registry_host: registry.yandex.net
          tag: '2'
      network_defaults:
        network_id: _YANDEXPAY_TEST_NETS_
      patchers_revision: 11
      pod_agent_sandbox_info:
        revision: 2621390537
      multi_cluster_replica_set:
        replica_set:
          clusters:
          - cluster: sas
            spec:
              constraints:
                antiaffinity_constraints:
                - key: rack
                  max_pods: 1
              replica_count: 1
          - cluster: vla
            spec:
              constraints:
                antiaffinity_constraints:
                - key: rack
                  max_pods: 1
              replica_count: 1
          deployment_strategy:
            max_unavailable: 2
          pod_template_spec:
            spec:
              disk_volume_requests:
              - id: disk-0
                labels:
                  used_by_infra: true
                quota_policy:
                  bandwidth_guarantee: 7864320
                  bandwidth_limit: 3932160
                  capacity: 2684354560
                storage_class: hdd
              host_infra:
                monitoring:
                  pod_agent:
                    add_pod_agent_user_signals: true
                  unistats:
                  - output_format: yasm_json
                    path: /unistat
                    port: 8080
                    workload_id: api
                  - output_format: yasm_json
                    path: /unistat
                    port: 8000
                    workload_id: api
              pod_agent_payload:
                spec:
                  boxes:
                  - compute_resources:
                      memory_guarantee: 1073741824
                      memory_limit: 1073741824
                      vcpu_guarantee: 200
                      vcpu_limit: 200
                    env:
                    - name: YENV_TYPE
                      value:
                        literal_env:
                          value: production
                    id: api
                    rootfs: {}
                    static_resources:
                    - mount_point: /opt/bin
                      resource_ref: PgPinger2007673887
                    - mount_point: /config/local
                      resource_ref: ApplicationConfigOverride
                    - mount_point: /nginx
                      resource_ref: NginxBinary
                    volumes:
                    - mode: read_write
                      mount_point: /ephemeral
                      volume_ref: ephemeral
                  mutable_workloads:
                  - workload_ref: api
                  resources:
                    layers:
                    - checksum: 'EMPTY:'
                      id: bionic-app
                      url: sbr:2527306889
                    static_resources:
                    - id: NginxBinary
                      url: sbr:2383206246
                      verification:
                        check_period_ms: 180000
                        checksum: MD5:576f025c1f98e1688c4e254f35fdbf50
                    - id: PgPinger2007673887
                      url: rbtorrent:4ee4e5365d3f0efd1391612ae1c3aeba1f8b5ee8
                      verification:
                        check_period_ms: 180000
                        checksum: MD5:1f182d0e04d65b5b21285e80774a2002
                    - access_permissions: '660'
                      files:
                        files:
                        - file_name: settings.py
                          secret_data:
                            alias: app-settings
                            decode_base64: true
                            id: production
                      id: ApplicationConfigOverride
                      verification:
                        check_period_ms: 180000
                        checksum: 'EMPTY:'
                  volumes:
                  - id: ephemeral
                  - id: push-agent-logs
                  workloads:
                  - box_ref: api
                    id: api
                    readiness_check:
                      http_get:
                        any: true
                        path: /ping
                        port: 80
                    start: {}
                    stop_policy:
                      container:
                        command_line: /bin/bash -c 'supervisorctl stop nginx && supervisorctl
                          stop all'
                        time_limit:
                          max_execution_time_ms: 30000
                          max_restart_period_ms: 10000
                          min_restart_period_ms: 10000
                      max_tries: 3
                    transmit_logs: true
              resource_requests:
                memory_guarantee: 1073741824
                memory_limit: 1073741824
                network_bandwidth_guarantee: 10485760
                vcpu_guarantee: 200
                vcpu_limit: 200
              secret_refs:
                app-settings:
                  secret_id: sec-01g3jmv8s0vs9kp30pqqbgsssv
                  secret_version: ver-01g3jmv8sfhaxqnjehz9rqmwwq
      revision: 1
    workers:
      images_for_boxes:
        workers:
          digest: 'EMPTY:'
          name: yandex-pay-sprint/yandex-pay-sprint
          registry_host: registry.yandex.net
          tag: '2'
      multi_cluster_replica_set:
        replica_set:
          clusters:
          - cluster: sas
            spec:
              constraints:
                antiaffinity_constraints:
                - key: rack
                  max_pods: 1
              replica_count: 1
          - cluster: vla
            spec:
              constraints:
                antiaffinity_constraints:
                - key: rack
                  max_pods: 1
              replica_count: 1
          deployment_strategy:
            max_unavailable: 2
          pod_template_spec:
            spec:
              disk_volume_requests:
              - id: infra
                labels:
                  used_by_infra: true
                quota_policy:
                  bandwidth_guarantee: 7864320
                  bandwidth_limit: 3932160
                  capacity: 2684354560
                storage_class: hdd
              host_infra:
                monitoring:
                  pod_agent:
                    add_pod_agent_user_signals: true
                  unistats:
                  - output_format: yasm_json
                    path: /unistat
                    port: 8001
                    workload_id: workers
              pod_agent_payload:
                spec:
                  boxes:
                  - compute_resources:
                      memory_guarantee: 1073741824
                      memory_limit: 1073741824
                      vcpu_guarantee: 200
                      vcpu_limit: 200
                    env:
                    - name: YENV_TYPE
                      value:
                        literal_env:
                          value: production
                    - name: APPLICATION_NAME
                      value:
                        literal_env:
                          value: workers
                    - name: SKIP_NGINX
                      value:
                        literal_env:
                          value: 'true'
                    - name: TASKQ_ACTION_WORKERS
                      value:
                        literal_env:
                          value: '5'
                    - name: DB_CONNECTION_MAXSIZE
                      value:
                        literal_env:
                          value: '20'
                    id: workers
                    rootfs: {}
                    static_resources:
                    - mount_point: /config/local
                      resource_ref: ApplicationConfigOverride
                    - mount_point: /opt/bin
                      resource_ref: PgPinger2007673887
                    volumes:
                    - mode: read_write
                      mount_point: /ephemeral
                      volume_ref: ephemeral
                  mutable_workloads:
                  - workload_ref: workers
                  resources:
                    layers:
                    - checksum: 'EMPTY:'
                      id: bionic-app
                      url: sbr:2527306889
                    static_resources:
                    - files:
                        files:
                        - file_name: settings.py
                          secret_data:
                            alias: app-settings
                            decode_base64: true
                            id: production
                      id: ApplicationConfigOverride
                      verification:
                        check_period_ms: 180000
                        checksum: 'EMPTY:'
                    - id: PgPinger2007673887
                      url: rbtorrent:4ee4e5365d3f0efd1391612ae1c3aeba1f8b5ee8
                      verification:
                        check_period_ms: 180000
                        checksum: MD5:1f182d0e04d65b5b21285e80774a2002
                  volumes:
                  - id: ephemeral
                  - id: push-agent-logs
                  workloads:
                  - box_ref: workers
                    id: workers
                    liveness_check:
                      http_get:
                        any: true
                        path: /ping
                        port: 8003
                        time_limit:
                          initial_delay_ms: 150000
                          max_execution_time_ms: 10000
                          max_restart_period_ms: 30000
                          min_restart_period_ms: 30000
                    readiness_check:
                      http_get:
                        expected_answer: ok
                        path: /check/workers-health
                        port: 8003
                        time_limit:
                          initial_delay_ms: 15000
                          max_execution_time_ms: 10000
                          max_restart_period_ms: 10000
                          min_restart_period_ms: 10000
                    transmit_logs: true
              resource_requests:
                memory_guarantee: 1073741824
                memory_limit: 1073741824
                network_bandwidth_guarantee: 10485760
                vcpu_guarantee: 200
                vcpu_limit: 200
              secret_refs:
                app-settings:
                  secret_id: sec-01g3jmv8s0vs9kp30pqqbgsssv
                  secret_version: ver-01g3jmv8sfhaxqnjehz9rqmwwq
      network_defaults:
        network_id: _YANDEXPAY_TEST_NETS_
      patchers_revision: 11
      pod_agent_sandbox_info:
        revision: 2621390537
      revision: 1
