export const SET_PARTNER_DATA_REQUEST = 'SET_PARTNER_DATA_REQUEST';
export const SET_PARTNER_DATA_FAILURE = 'SET_PARTNER_DATA_FAILURE';
export const SET_PARTNER_DATA_SUCCESS = 'SET_PARTNER_DATA_SUCCESS';
