export const FETCH_PARTNER_SUGGEST_REQUEST = 'FETCH_PARTNER_SUGGEST_REQUEST';
export const FETCH_PARTNER_SUGGEST_SUCCESS = 'FETCH_PARTNER_SUGGEST_SUCCESS';
export const FETCH_PARTNER_SUGGEST_FAILURE = 'FETCH_PARTNER_SUGGEST_FAILURE';
