export const FETCH_GEO_SUGGEST_REQUEST = 'FETCH_GEO_SUGGEST_REQUEST';
export const FETCH_GEO_SUGGEST_SUCCESS = 'FETCH_GEO_SUGGEST_SUCCESS';
export const FETCH_GEO_SUGGEST_FAILURE = 'FETCH_GEO_SUGGEST_FAILURE';
