dev-proxy: node _config/dev-server/proxy
tuneller: TUNNELER_HOST=ws1-tunnelerapi.tunneler-si.yandex-team.ru dk tun 3099:8080
playground: cd services/playground && npm start
pay-form: cd services/pay-form && npm start
sdk: cd services/sdk && npm start
sdk-init: cd services/sdk-init && npm start
sdk-init-speedup: cd services/sdk-init-speedup && npm start
sdk-payment-method: cd services/sdk-payment-method && npm start
server-tvmtool: cd server && npm run start-tvmtool
server: cd server && npm start
