export const FETCH_PARTNER_SUBMIT_REQUEST = 'FETCH_PARTNER_SUBMIT_REQUEST';
export const FETCH_PARTNER_SUBMIT_SUCCESS = 'FETCH_PARTNER_SUBMIT_SUCCESS';
export const FETCH_PARTNER_SUBMIT_FAILURE = 'FETCH_PARTNER_SUBMIT_FAILURE';

export const FETCH_PARTNER_MERCHANTS_REQUEST =
  'FETCH_PARTNER_MERCHANTS_REQUEST';
export const FETCH_PARTNER_MERCHANTS_SUCCESS =
  'FETCH_PARTNER_MERCHANTS_SUCCESS';
export const FETCH_PARTNER_MERCHANTS_FAILURE =
  'FETCH_PARTNER_MERCHANTS_FAILURE';

export const FETCH_PROVIDER_SUBMIT_REQUEST = 'FETCH_PROVIDER_SUBMIT_REQUEST';
export const FETCH_PROVIDER_SUBMIT_SUCCESS = 'FETCH_PROVIDER_SUBMIT_SUCCESS';
export const FETCH_PROVIDER_SUBMIT_FAILURE = 'FETCH_PROVIDER_SUBMIT_FAILURE';

export const FETCH_PROVIDER_APPLICATION_SUBMIT_REQUEST =
  'FETCH_PROVIDER_APPLICATION_SUBMIT_REQUEST';
export const FETCH_PROVIDER_APPLICATION_SUBMIT_SUCCESS =
  'FETCH_PROVIDER_APPLICATION_SUBMIT_SUCCESS';
export const FETCH_PROVIDER_APPLICATION_SUBMIT_FAILURE =
  'FETCH_PROVIDER_APPLICATION_SUBMIT_FAILURE';

export const PATCH_PARTNER_SUBMIT_REQUEST = 'PATCH_PARTNER_SUBMIT_REQUEST';
export const PATCH_PARTNER_SUBMIT_SUCCESS = 'PATCH_PARTNER_SUBMIT_SUCCESS';
export const PATCH_PARTNER_SUBMIT_FAILURE = 'PATCH_PARTNER_SUBMIT_FAILURE';
